apiVersion: v1
kind: Service
metadata:
  name: hello-port-railway
  namespace: default
  labels:
    app: hello-port-railway
    managed-by: port
spec:
  type: ClusterIP
  selector:
    app: hello-port-railway
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
